# Generated by Django 5.2.7 on 2025-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0003_requestlog_city_requestlog_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField(help_text='Reason why this IP is flagged as suspicious')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, help_text='Whether this suspicious activity has been reviewed')),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='ip_tracking_ip_addr_c8d8c6_idx'), models.Index(fields=['is_resolved'], name='ip_tracking_is_reso_ccfb1f_idx')],
            },
        ),
    ]
